name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.106'
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore Fituska/Fituska.sln
    - name: Build
      run: dotnet build Fituska/Fituska.sln --no-restore
    - name: Test
      run: dotnet test Fituska/Fituska.sln --no-build --verbosity normal
